---
Gemfile:
  required:
    ':test':
      - gem: rake
      - gem: rspec-puppet
        git: https://github.com/rodjek/rspec-puppet.git
      - gem: puppet-lint
        git: https://github.com/rodjek/puppet-lint.git
      - gem: metadata-json-lint
      - gem: rspec-puppet-facts
      - gem: rspec
      - gem: puppet-blacksmith
        git: https://github.com/voxpupuli/puppet-blacksmith.git
      - gem: voxpupuli-release
        git: https://github.com/voxpupuli/voxpupuli-release-gem.git
      - gem: rubocop
        version: '0.35.0'
      - gem: rspec-puppet-utils
      - gem: puppetlabs_spec_helper
      - gem: puppet-lint-absolute_classname-check
      - gem: puppet-lint-leading_zero-check
      - gem: puppet-lint-trailing_comma-check
      - gem: puppet-lint-version_comparison-check
      - gem: puppet-lint-classes_and_types_beginning_with_digits-check
      - gem: puppet-lint-unquoted_string-check
      - gem: puppet-lint-variable_contains_upcase
      - gem: mocha
    ':development':
      - gem: travis
      - gem: travis-lint
      - gem: guard-rake
    ':system_tests':
      - gem: beaker
      - gem: beaker-rspec
      - gem: beaker-puppet_install_helper
        require: false
spec/spec_helper.rb:
  unmanaged: true
