---
spec/spec_helper.rb:
  unmanaged: true
.travis.yml:
  secure: "CUoA5hahC6sF2E8UNC9xkxA+Hn0nggAOv/bfRvs2yJYjdDnJelq13d7Hp3ty6YHOp533H5bGtuSp2lxRLLIKsTLiDyEGX/wITpVCoD6DUnJKBtKLJ6Z/kdcYgwBCb6uVC5kU2H6cyMzpdhV2MArvSx5UTVhxXj6ktyri/tNkszM="
